spring.application.name=Wallet-Service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=nicolas
spring.datasource.password=nicolas

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true