spring.application.name=AUTH-SERVICE

server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/auth_db
spring.datasource.username=nicolas
spring.datasource.password=nicolas

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret=QqK8bHx9kT1RzM3WqY5eVb6gA2tJx0PnL8sFd4uH9wI=

spring.jpa.hibernate.ddl-auto=update

# EUREKA

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka