spring.application.name=AUTH-SERVICE

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=nicolas
spring.datasource.password=nicolas

jwt.secret=QqK8bHx9kT1RzM3WqY5eVb6gA2tJx0PnL8sFd4uH9wI=

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka