#spring.application.name=API-GATEWAY
#
#server.port=8080
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#
#spring.cloud.gateway.routes[0].id=auth-service
#spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
#
##spring.cloud.gateway.routes[1].id=wallet-service
##spring.cloud.gateway.routes[1].uri=lb://WALLET-SERVICE
##spring.cloud.gateway.routes[1].predicates[1]=Path=/wallet/**

spring.application.name=API-GATEWAY

server.port=8080

# =========================
# EUREKA
# =========================

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# =========================
# GATEWAY ROUTES
# =========================

# AUTH SERVICE

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# WALLET SERVICE

spring.cloud.gateway.routes[1].id=wallet-service
spring.cloud.gateway.routes[1].uri=lb://WALLET-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/wallet/**

# NOTIFICATION SERVICE

spring.cloud.gateway.routes[2].id=notification-service
spring.cloud.gateway.routes[2].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/notification/**